### ISSUE TITLE
Global settings for adding this enrolment method to new courses

### ISSUE THREAD

**Issue by anna-sparkfore** [sokunthearithmakara/enrol_gapply#12]
A valuable improvement would be to have the option of automatically adding this enrolment method to all new courses via global settings, e.g. like in enrol_apply:
![image](https://github.com/sokunthearithmakara/enrol_gapply/assets/175125408/ea3599c4-b01b-460e-84fd-b0c87f9047b3)

**Comment by sokunthearithmakara** [comment]
The setting has been added in version 1.0.7.
