### ISSUE TITLE
Global setting for notifying only admins in corresponding course

### ISSUE THREAD

**Issue by anna-sparkfore** [sokunthearithmakara/enrol_gapply#13]
Is it correctly understood that all users with the capability to "Manage enrollment applications" will receive the notification sent upon application?
![image](https://github.com/sokunthearithmakara/enrol_gapply/assets/175125408/372f6987-3e6a-4c46-b866-be72e23c19cb)

If so, maybe you could consider adding a global setting for only notifying teachers or managers assigned to the specific course, similar to this setting from another plugin enrol_apply:
![image](https://github.com/sokunthearithmakara/enrol_gapply/assets/175125408/40d8269d-cfa4-4f73-98e5-045f1afb0e3a)

**Comment by sokunthearithmakara** [comment]
You are right; the notification is sent to users with the Manage Enrollment Applications capability. However, this capability is at the course context level, meaning only users (editing teachers and managers by default) within the specific course will receive the notification.

**Comment by anna-sparkfore** [comment]
I know this issue is closed, but we have the unwanted behaviour that all site admins and managers of the site are notified whenever a new application is submitted. I tried it again now:
* We have 1 site admin and 1 manager - none of them are enrolled in the course containing the application/enrol_gapply
* We have 1 teacher enrolled in the course containing the application/enrol_gapply

The result is that the notification "New application request for X" is sent to 
* the site admin
* the manager
* the course teacher

We'd really appreciate if you please can reconsider the possibility to add a global setting for restricting the notification to teachers or managers assigned to the specific course. Or another solution with the same outcome.

**Comment by sokunthearithmakara** [comment]
@anna-sparkfore I was able to reproduce your issue and applied the fix to address it. Please update your plugin and let me know if you still encounter the issue on your end.
