### ISSUE TITLE
Site admin presets failes when enrol_gapply is installed

### ISSUE THREAD

**Issue by anna-sparkfore** [sokunthearithmakara/enrol_gapply#14]
We can't create any site admin presets when this plugin is installed. If we uninstall it, the preset can be created.

Use case
1. Install the plugin enrol_gapply in a Moodle LMS site
2. Go to Site administration > General > Site admin presets 
3. Click Create preset
4. Add a title and click Create preset
Currently the last step results in an error message:
![image](https://github.com/sokunthearithmakara/enrol_gapply/assets/175125408/25eecf13-21fb-4288-848d-b8d1ed1590b1)

[generalexceptionmessage](https://docs.moodle.org/403/en/error/moodle/generalexceptionmessage)

**Comment by sokunthearithmakara** [comment]
Thank you for spotting this. It has been resolved in version 1.0.7.
