### ISSUE TITLE
Error with Moodle 4.4.2

### ISSUE THREAD

**Issue by nelliemuller** [sokunthearithmakara/enrol_gapply#15]
I get this error message when I try to add the enrollment method:

Stack trace:
line 240 of /enrol/gapply/lib.php: TypeError thrown
line 240 of /enrol/gapply/lib.php: call to explode()
line 50 of /enrol/editinstance_form.php: call to enrol_gapply_plugin->edit_instance_form()
line 217 of /lib/formslib.php: call to enrol_instance_edit_form->definition()
line 76 of /enrol/editinstance.php: call to moodleform->__construct()

**Comment by sokunthearithmakara** [comment]
@nelliemuller Thanks for reporting the issue. I released a new version on the Moodle Plugin directory that addressed this issue. Please upgrade your plugin.
