### ISSUE TITLE
Notifications are sent in the language of the teacher not the language of the recieving student

### ISSUE THREAD

**Issue by anna-sparkfore** [sokunthearithmakara/enrol_gapply#17]
In our use case, the Teacher has another preferred language than the applicants.

When I have a Teacher with Language preference = Swedish and a Student with Language preference set to English, the Student receives the notfication emails in Swedish i.e. the language of the teacher, not the language of the receiver.
- applicationwaitlist
- applicationreject
- applicationapproved

The same issue applies to the notification emails to the Teacher: The notification 
"New application request" is sent in the preferred language of the Student, not the language of the receiving Teacher.

For other (Moodle core) notification emails, e.g. Course content changes the notification is sent in the preferred language of the receipient.

**Comment by sokunthearithmakara** [comment]
@anna-sparkfore Interesting use case. I added an option to send notifications in the recipient's preferred language in the site settings.
![image](https://github.com/user-attachments/assets/6e22ad80-0001-42ee-a48f-40defdc450a4)
