### ISSUE TITLE
Non-consistent redirection in 'choose group' modal

### ISSUE THREAD

**Issue by mickaelclavreul** [sokunthearithmakara/enrol_gapply#18]
Hi,

When trying to approve/reject/delete applications on our platform (Moodle 4.3.x), the current page refreshes itself and the approval is not applied.
I found out that one redirection from the "choose group" modal is using a relative url `/enrol/gapply/ajax.php` which does not work in our current infrastructure configuration.
The relative url can be found in [amd/src/custom.js](https://github.com/sokunthearithmakara/enrol_gapply/blob/c07acc182acba05d8aa3df020d99272c5c6702b1/amd/src/custom.js) at line 313. If I concatenate config.php `wwwroot` string to the given url as `url: M.cfg.wwwroot + "/enrol/gapply/ajax.php"`, everything is fine :)

Hope this helps.

**Comment by mickaelclavreul** [comment]
Hi again,

I found out another problematic link generation item in [manage.php](https://github.com/sokunthearithmakara/enrol_gapply/blob/c07acc182acba05d8aa3df020d99272c5c6702b1/manage.php) on line 116.
Return url when editing an enrolment instance does not contains the full server path.
I changed:
`'returnurl' => '/enrol/gapply/manage.php?id=' . $id . '&tab=' . $tab`
to
`'returnurl' => new moodle_url('/enrol/gapply/manage.php',['id' => $id ,'tab'=> $tab])'`

Please let me know if it's the proper way to do it.

**Comment by sokunthearithmakara** [comment]
@mickaelclavreul: Thanks for spotting these. The fixes will be included in the upcoming release.
