### ISSUE TITLE
[Feature] Default enrolment role

### ISSUE THREAD

**Issue by mickaelclavreul** [sokunthearithmakara/enrol_gapply#19]
Hi,

When approving an application, your plugin tries to assign default role '5' (Student) to the user but it depends on Moodle configuration.
I added a new setting entry to your plugin, similar to the one from manual enrolment, that allows to select a default enrolment role for users.
In [settings.php](https://github.com/sokunthearithmakara/enrol_gapply/blob/c07acc182acba05d8aa3df020d99272c5c6702b1/settings.php), line 78, I added the following code to propose a default enrolment role:
```
if (!during_initial_install()) {
  $options = get_default_enrol_roles(context_system::instance());
  $student = get_archetype_roles('student');
  $student = reset($student);
  $settings->add(new admin_setting_configselect('enrol_gapply/roleid',
  get_string('defaultrole', 'role'), '', $student->id ?? null, $options));
}
```
In [ajax.php](https://github.com/sokunthearithmakara/enrol_gapply/blob/c07acc182acba05d8aa3df020d99272c5c6702b1/ajax.php), I changed your code to retrieve the `roleid` from settings and called the `enrol_user` function with it:
```
$roleid = get_config('enrol_gapply','roleid');
$enrol->enrol_user($instance, $record->userid, $roleid, $instance->enrolstartdate, $instance->enrolenddate);
```

I'm not an experienced Moodle plugin contributor so please feel free to improve it !

Do you think you can also integrate the selection of a role when we add a new enrolment method instance of your plugin, in the same way as manual, cohort or self propose?

**Comment by sokunthearithmakara** [comment]
Thanks for the suggestion. This is available in 1.0.9.
- Set default role at site level
- Set default role at course level
- Select role per specific application
![image](https://github.com/user-attachments/assets/1cc49819-58ce-4c6f-aa9c-088ec8bc8a29)
