### ISSUE TITLE
[New feature] Cancel your application

### ISSUE THREAD

**Issue by anna-sparkfore** [sokunthearithmakara/enrol_gapply#20]
I got the feedbaack from some teachers that it would be useful if a user could cancel their application from the enrol page with a new button "Withdraw my application". A user would then have to confirm in a modal that "Are you sure you want to cancel your application? This means that your application details will be deleted."

Would that be possible to add?

![image](https://github.com/user-attachments/assets/be6dc666-dda4-4978-9556-040187f96cca)

**Comment by sokunthearithmakara** [comment]
This is added in 1.0.9. 
- This must be enabled in the enrollment instance form.
- Applicable to new (unprocessed) applications only.

![image](https://github.com/user-attachments/assets/0f59f582-47de-4654-86bb-4d196b90e330)

**Comment by anna-sparkfore** [comment]
Wow thank you so much!
