### ISSUE TITLE
enrol_gapply_pluginfile doesn't have any permission checks

### ISSUE THREAD

**Issue by danmarsden** [sokunthearithmakara/enrol_gapply#8]
I'm not completely clear what the files are that the enrol_gapply plugins stores, but the enrol_gapply_pluginfile function doesn't seem to perform any capability checks to see if the user should be able to view the files - are these files available to alll users (including anonymous users to the site) or should there be a capability check in there to make sure the user should be able to view the files in the context/ associated with this course or this user?

**Comment by sokunthearithmakara** [comment]
@danmarsden this is intentional. The application attachments are publically accessible although I do have a capability check when it comes to who can review the submitted applications.
